package TicTacToeGame;

import java.awt.Color;

/*
 * The frame players will see when they start the game
 */

public class StartScreen extends javax.swing.JFrame {

    private GameDataModel myModel;
    private GameController myController;
    
    //Creates new form StartScreen
    public StartScreen(GameDataModel myModel, GameController myController) {
        this.myModel = myModel;
        this.myController = myController;
        initComponents();
        getContentPane().setBackground(new Color(121, 208, 195));
        // for when user presses back button
        if (myModel.selectedGameMode()) {
            if (myModel.isTwoPlayers()) {
                jRadioButtonTwoPlayers.setSelected(true);
            } else {
                jRadioButtonPlayComputer.setSelected(true);
            }
            jPlayButton.setEnabled(true);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playType = new javax.swing.ButtonGroup();
        jLabelWelcome = new javax.swing.JLabel();
        jLabelSelect = new javax.swing.JLabel();
        jRadioButtonTwoPlayers = new javax.swing.JRadioButton();
        jRadioButtonPlayComputer = new javax.swing.JRadioButton();
        jPlayButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelWelcome.setText("Welcome to TicTacToe!");

        jLabelSelect.setText("Select an option below:");

        playType.add(jRadioButtonTwoPlayers);
        jRadioButtonTwoPlayers.setText("Two Players");
        jRadioButtonTwoPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTwoPlayersActionPerformed(evt);
            }
        });

        playType.add(jRadioButtonPlayComputer);
        jRadioButtonPlayComputer.setText("Play against the Computer");
        jRadioButtonPlayComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPlayComputerActionPerformed(evt);
            }
        });

        jPlayButton.setText("Play!");
        jPlayButton.setEnabled(false);
        jPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWelcome)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 291, Short.MAX_VALUE)
                .addComponent(jPlayButton)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonTwoPlayers)
                    .addComponent(jLabelSelect)
                    .addComponent(jRadioButtonPlayComputer))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelWelcome)
                .addGap(19, 19, 19)
                .addComponent(jLabelSelect)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonTwoPlayers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPlayComputer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPlayButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTwoPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTwoPlayersActionPerformed

        jPlayButton.setEnabled(true);
        myModel.setTwoPlayers(true);
        
    }//GEN-LAST:event_jRadioButtonTwoPlayersActionPerformed

    private void jRadioButtonPlayComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPlayComputerActionPerformed
        
        jPlayButton.setEnabled(true);
        myModel.setTwoPlayers(false);
    }//GEN-LAST:event_jRadioButtonPlayComputerActionPerformed

    //when the play button is pressed go to the PlayerEntryDialog frame and close this one
    private void jPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayButtonActionPerformed

        PlayerEntryDialog getPlayers = new PlayerEntryDialog(myModel, myController);
        getPlayers.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jPlayButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSelect;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JButton jPlayButton;
    private javax.swing.JRadioButton jRadioButtonPlayComputer;
    private javax.swing.JRadioButton jRadioButtonTwoPlayers;
    private javax.swing.ButtonGroup playType;
    // End of variables declaration//GEN-END:variables
}
